[project]
name = "py-robot-fw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docutils>=0.22.2",
    "robotframework>=7.3.2",
    "robotframework-lint>=1.1",
    "robotframework-seleniumlibrary>=6.7.1",
]
