import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import Script from 'next/script';
import Header from '../components/Header';
import SidePanel from '../components/SidePanel';
import './globals.css';

const notoSansJp = Noto_Sans_JP({
  variable: '--font-sans',
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){
            try {
              var key='theme';
              var stored=localStorage.getItem(key);
              if (stored === 'light' || stored === 'dark') {
                document.documentElement.setAttribute('data-theme', stored);
              } else {
                // system: 属性を外して OS の設定に追従
                document.documentElement.removeAttribute('data-theme');
              }
            } catch (e) {}
          })();`}
        </Script>
      </head>
      <body className={`${notoSansJp.variable} antialiased`}>
        <Header />
        <div className="pr-4">
          <div className="flex items-stretch gap-6 min-h-[calc(100vh-49px)]">
            <aside className="w-56 shrink-0 py-4">
              <SidePanel />
            </aside>
            <div aria-hidden className="self-stretch w-px bg-foreground/15" />
            <main className="flex-1 min-w-0 py-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
