exclude = [
  ".venv"
]
target-version = "py312"
line-length = 99
indent-width = 2

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint]
select = ["ALL"]
extend-ignore = ["T201", "D400", "D415", "INP001", "RUF002"]
